name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Clear pnpm store
        run: pnpm store prune

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 运行测试
      - run: pnpm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 使用锁定文件安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 发布到 npm
      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}